spring:
  profiles:
    active: "dev"


---

spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/skladio_dev
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver